version: "3"
services:
  orthanc1:
    build:
      context: ./orthanc1
      dockerfile: Dockerfile
    container_name: orthanc1
    ports:
      - "8042:8042"
    volumes:
      - "./orthanc1/orthanc1.json:/etc/orthanc/orthanc.json:ro"  # Đảm bảo đúng đường dẫn
    restart: always
    networks:
      - dicom-network

  orthanc2:
    build:
      context: ./orthanc2
      dockerfile: Dockerfile
    container_name: orthanc2
    ports:
      - "8043:8043"
    volumes:
      - "./orthanc2/orthanc2.json:/etc/orthanc/orthanc.json:ro"
    restart: always
    networks:
      - dicom-network

networks:
  dicom-network:
    driver: bridge
