version: "3"
services:
  hospital_pacs:
    image: jodogne/orthanc-plugins:latest
    build:
      context: ./hospital_pacs
      dockerfile: Dockerfile
    container_name: hospital_pacs
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - "./hospital_pacs/orthanc1.json:/etc/orthanc/orthanc.json:ro"
    restart: always
    networks:
      - dicom-network

  research_pacs:
    image: jodogne/orthanc-plugins:latest
    build:
      context: ./research_pacs
      dockerfile: Dockerfile
    container_name: research_pacs
    ports:
      - "8043:8042"   # gắn cổng HTTP container 8042 ra ngoài bằng 8043
      - "4243:4242"   # gắn cổng DICOM container 4242 ra ngoài bằng 4243
    volumes:
      - "./research_pacs/orthanc2.json:/etc/orthanc/orthanc.json:ro"
    restart: always
    networks:
      - dicom-network

networks:
  dicom-network:
    driver: bridge
