version: '3'
services:
  orthanc1:
    image: jodogne/orthanc:latest
    container_name: orthanc1
    ports:
      - "8042:8042" # Cổng cho orthanc1
    volumes:
      - "D:/vhproj/dicom-relay/orthanc1/Orthanc.json:/etc/orthanc/orthanc.json:ro"
    restart: always

  orthanc2:
    image: jodogne/orthanc:latest
    container_name: orthanc2
    ports:
      - "8043:8043" # Cổng cho orthanc2
    volumes:
      - "D:/vhproj/dicom-relay/orthanc2/Orthanc.json:/etc/orthanc/orthanc.json:ro"
    restart: always
