version: "3"
services:
  orthanc1:
    image: jodogne/orthanc-plugins:latest
    build:
      context: ./orthanc1
      dockerfile: Dockerfile
    container_name: orthanc1
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - "./orthanc1/orthanc1.json:/etc/orthanc/orthanc.json:ro"
    restart: always
    networks:
      - dicom-network

  orthanc2:
    image: jodogne/orthanc-plugins:latest
    build:
      context: ./orthanc2
      dockerfile: Dockerfile
    container_name: orthanc2
    ports:
      - "8043:8043"
      - "4243:4242"   # Lưu ý: 4242 là cổng nội bộ, 4243 chỉ cho truy cập host bên ngoài
    volumes:
      - "./orthanc2/orthanc2.json:/etc/orthanc/orthanc.json:ro"
    restart: always
    networks:
      - dicom-network

networks:
  dicom-network:
    driver: bridge
